# Generated by Django 5.2.7 on 2025-11-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financecategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
