# Generated by Django 5.2.7 on 2025-11-12 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_qrcode_file'),
        ('finance', '0002_alter_financecategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='financetransaction',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer'),
        ),
    ]
