# Generated by Django 5.2.7 on 2025-12-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('VND', 'Việt Nam Đồng (VNĐ)'), ('CNY', 'Đồng Nhân dân tệ (CNY)')], default='CNY', max_length=10, verbose_name='Loại tiền tệ'),
        ),
    ]
