# Generated by Django 5.2.7 on 2025-11-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='qr/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
