# Generated by Django 5.2.7 on 2025-11-11 14:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
