# Generated by Django 5.2.7 on 2025-12-15 11:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên ví')),
                ('currency', models.CharField(default='CNY', max_length=10, verbose_name='Loại tiền tệ')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Số dư')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
            options={
                'verbose_name': 'Ví',
                'verbose_name_plural': 'Ví',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Nạp tiền'), ('withdrawal', 'Rút tiền / Chi tiêu')], max_length=20, verbose_name='Loại giao dịch')),
                ('category', models.CharField(choices=[('purchase', 'Mua hàng'), ('shipping', 'Phí vận chuyển'), ('deposit', 'Nạp tiền'), ('refund', 'Hoàn tiền'), ('other', 'Khác')], default='other', max_length=50, verbose_name='Danh mục')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Số tiền')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('reference_code', models.CharField(blank=True, max_length=100, verbose_name='Mã tham chiếu')),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày giao dịch')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet', verbose_name='Ví')),
            ],
            options={
                'verbose_name': 'Giao dịch',
                'verbose_name_plural': 'Giao dịch',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
