# Generated by Django 5.2.7 on 2025-12-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_wallet_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Nạp tiền'), ('withdrawal', 'Rút tiền / Chi tiêu'), ('income', 'Khoản thu'), ('expense', 'Khoản chi')], max_length=20, verbose_name='Loại giao dịch'),
        ),
    ]
