# Generated by Django 5.2.7 on 2025-11-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sale_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
